[build]
  command = "npm ci --include=dev && npm run build"
  functions = "netlify/functions"
  publish = "server/public"

[[redirects]]

  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }
  
[context.develop]
  environment = { NODE_ENV = "development" }
